In [1]:
import torch

In [9]:
a = torch.arange(0,6).reshape(2,3)
b = torch.arange(0,6).reshape(3,2)
a,b, a @ b

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[10, 13],
         [28, 40]]),
 tensor([[ 3,  4,  5],
         [ 9, 14, 19],
         [15, 24, 33]]))

In [7]:
# 
result1 = torch.zeros((2,2))
for i in range(2):
    for j in range(2):
        for k in range(3):
            result1[i][j] = a[i][k] * b[k][j]
result1

tensor([[ 8., 10.],
        [20., 25.]])

In [ ]:
result2 = torch.zeros((2,2))
for